"""create assosiactionpost_cat and post_tag table

Revision ID: 5b67c72e7704
Revises: e058b009e2c5
Create Date: 2026-01-23 13:18:17.657062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b67c72e7704"
down_revision: Union[str, Sequence[str], None] = "e058b009e2c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_category",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categorys.id"],
            name=op.f("fk_post_category_category_id_categorys"),
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name=op.f("fk_post_category_post_id_posts"),
        ),
        sa.PrimaryKeyConstraint(
            "post_id", "category_id", name=op.f("pk_post_category")
        ),
    )
    op.create_table(
        "post_tag",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_post_tag_post_id_posts")
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_post_tag_tag_id_tags")
        ),
        sa.PrimaryKeyConstraint("post_id", "tag_id", name=op.f("pk_post_tag")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_tag")
    op.drop_table("post_category")
    # ### end Alembic commands ###
