"""fix relationship

Revision ID: f892946c9a25
Revises: 0621eedaa1fb
Create Date: 2026-02-17 20:23:54.473002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f892946c9a25"
down_revision: Union[str, Sequence[str], None] = "0621eedaa1fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("author_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_posts_author_id_users"),
        "posts",
        "users",
        ["author_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_posts_author_id_users"), "posts", type_="foreignkey"
    )
    op.drop_column("posts", "author_id")
    # ### end Alembic commands ###
