"""create category table

Revision ID: 59cd8ad3b515
Revises: b0210f551902
Create Date: 2026-01-23 12:28:47.595363

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59cd8ad3b515"
down_revision: Union[str, Sequence[str], None] = "b0210f551902"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categorys")),
        sa.UniqueConstraint("name", name=op.f("uq_categorys_name")),
    )
    op.create_index(op.f("ix_categorys_slug"), "categorys", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categorys_slug"), table_name="categorys")
    op.drop_table("categorys")
    # ### end Alembic commands ###
